mqtt:
  broker_uri: "tcp://${MQTT_BROKER:-hivemq-broker}:${MQTT_PORT:-1883}"
  client_id: "bt_controller"
  uns_topic: "NN/Nybrovej/InnoLab"

aas:
  server_url: "http://${AAS_SERVER:-aas-env}:${AAS_PORT:-8081}"
  registry_url: "http://${AAS_REGISTRY:-aas-registry}:${AAS_REGISTRY_PORT:-8080}"
  asset_ids:
    - "https://smartproductionlab.aau.dk/assets/aauFillingLine"

groot2:
  port: 1667

behavior_tree:
  generate_xml_models: false
  description_path: "../../BTDescriptions/production.xml"
  nodes_path: "../../BTDescriptions/tree_nodes_model.xml"