mqtt:
  broker_uri: "tcp://192.168.0.104:1883"
  client_id: "bt_controller"
  uns_topic: "NN/Nybrovej/InnoLab"

aas:
  server_url: "http://192.168.0.104:8081"
  registry_url: "http://192.168.0.104:8082"
  asset_ids:
    - "https://smartproductionlab.aau.dk/assets/aauFillingLine"

groot2:
  port: 1667

behavior_tree:
  generate_xml_models: false
  description_path: "../../BTDescriptions/production.xml"
  nodes_path: "../../BTDescriptions/tree_nodes_model.xml"