mqtt:
  broker_uri: "tcp://192.168.0.104:1883"
  client_id: "bt_controller"
  uns_topic: "NN/Nybrovej/InnoLab"

aas:
  server_url: "http://192.168.0.104:8081"
  registry_url: "http://192.168.0.104:8082"

groot2:
  port: 1667

behavior_tree:
  generate_xml_models: false
  description_path: "../config/tree.xml"
  nodes_path: "../config/bt_description/tree_nodes_model.xml"