aauFillingLine:
    idShort: aauFillingLine
    id: 'https://smartproductionlab.aau.dk/aas/aauFillingLineAAS'
    globalAssetId: 'https://smartproductionlab.aau.dk/assets/MWQ2ODY5ZDEtZTQ3Yy00NWU4LTlmYTAtNTI3YjVlMDk4MWFi'
    derivedFrom: 'https://smartproductionlab.aau.dk/aas/templates/resource'
    assetType: 'https://smartproductionlab.aau.dk/Resource/CPPS/AsepticFillingLine/aauFillingLine'
    serialNumber: 'AAU-FL-2024-001'
    location: 'InnoLab, Nybrovej, AAU'
    AssetInterfacesDescription:
    Variables:
    Parameters:
    HierarchicalStructures:
        Name: 'BillOfMaterials'

    # Capabilities:
    #     - dispenseing:
    #         realizedBy: "dispense"
    
    # Skills:
        # dispense:
        #     description: "dispenseing function for pharmaceutical primary packaging"
        #     semantic_id: "https://smartproductionlab.aau.dk/dispenseing"
        #     input_variable:
        #         Uuid: "string"
        #     output_variable:
        #         State: "string"
        #     in_ouput_variable:
        #     interface: "dispense"
        # Occupy:
        #     description: "dispenseing function for pharmaceutical primary packaging"
        #     semantic_id: "https://smartproductionlab.aau.dk/Occupy"
        #     input_variable:
        #         Uuid: "string"
        #     output_variable:
        #         State: "string"
        #     in_ouput_variable:
        #     interface: "occupy"
        # Release:
        #     description: "dispenseing function for pharmaceutical primary packaging"
        #     semantic_id: "https://smartproductionlab.aau.dk/Release"
        #     input_variable:
        #         Uuid: "string"
        #     output_variable:
        #         State: "string"
        #     in_ouput_variable:
        #     interface: "release"
        # Halt:
        #     description: "dispenseing function for pharmaceutical primary packaging"
        #     semantic_id: "https://smartproductionlab.aau.dk/Halt"
        #     input_variable:
        #         Uuid: "string"
        #     output_variable:
        #         State: "string"
        #     in_ouput_variable:
        #     interface: "halt"