optimaUnloadingSystemAAS:
    idShort: optimaUnloadingSystemAAS
    id: 'https://smartproductionlab.aau.dk/aas/optimaUnloadingSystemAAS'
    globalAssetId: 'https://smartproductionlab.aau.dk/assets/NGRjZjc0ODUtZTIxMi00ZGQxLWE3MzAtYmEzMDc1NTBlNmMx'
    derivedFrom: 'https://smartproductionlab.aau.dk/aas/templates/resource'
    assetType: 'https://smartproductionlab.aau.dk/Resource/CPPM/UnloadingSystem/optimaUnloadingSystem'
    serialNumber: 'OPTIMA-ULS-2024-001'
    location: 'InnoLab, Nybrovej, AAU'
    AssetInterfacesDescription:
        InterfaceMQTT:
            Title: 'optima Unloading System'
            EndpointMetadata:
                base: 'mqtt://192.168.0.104:1883/NN/Nybrovej/InnoLab/Unloading'
                contentType: 'application/json'
            InteractionMetadata:
                actions:
                    Unloading:
                        key: 'Unloading'
                        title: 'Unloading'
                        synchronous: 'true'
                        input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
                        output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json'
                        forms:
                            contentType: 'application/json'
                            href: '/CMD/Unloading'
                            op: 'invokeAction'
                            mqv_retain: 'false'
                            mqv_controlPacket: subscribe
                            mqv_qos: '2'
                            response:
                                contentType: 'application/json'
                                href: '/DATA/Unloading'
                                mqv_controlPacket: 'publish'
                    Halt:
                        key: 'Halt'
                        title: 'Halt'
                        synchronous: 'true'
                        input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
                        forms:
                            contentType: 'application/json'
                            href: '/CMD/Halt'
                            op: 'invokeAction'
                            mqv_retain: 'false'
                            mqv_controlPacket: subscribe
                            mqv_qos: '2'                                   
                    Occupy:
                        key: 'Occupy'
                        title: 'Occupy'
                        synchronous: 'true'
                        input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
                        output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json'
                        forms:
                            contentType: 'application/json'
                            href: '/CMD/Occupy'
                            op: 'invokeAction'
                            mqv_retain: 'false'
                            mqv_controlPacket: subscribe
                            mqv_qos: '2'
                            response:
                                contentType: 'application/json'
                                href: '/DATA/Occupy'
                                mqv_controlPacket: 'publish'
                    Release:
                        key: 'Release'
                        title: 'Release'
                        synchronous: 'true'
                        input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
                        output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json'
                        forms:
                            contentType: 'application/json'
                            href: '/CMD/Release'
                            op: 'invokeAction'
                            mqv_retain: 'false'
                            mqv_controlPacket: subscribe
                            mqv_qos: '2'
                            response:
                                contentType: 'application/json'
                                href: '/DATA/Release'
                                mqv_controlPacket: 'publish'
                properties:
                    StationState:
                        key: 'StationState'
                        title: 'StationState'
                        output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/stationState.schema.json'
                        forms:
                            contentType: 'application/json'
                            href: '/DATA/State'
                            mqv_retain: 'false'
                            mqv_controlPacket: publish
                            mqv_qos: '0'

    Variables:
        PackMLState:
            semanticId: 'https://www.omac.org/packml/state'
            InterfaceReference: 'StationState'
            Field: 'State'
        OccupationState:
            semanticId: 'https://smartproductionlab.aau.dk/stationOccupation'
            InterfaceReference: 'StationState'
            Field: 'ProcessQueue'
    Parameters:
    HierarchicalStructures:
        Name: 'BillOfMaterials'
        Archetype: 'OneUp'
        IsPartOf:
            aauFillingLineAAS:
                globalAssetId: 'https://smartproductionlab.aau.dk/assets/MWQ2ODY5ZDEtZTQ3Yy00NWU4LTlmYTAtNTI3YjVlMDk4MWFi'
    
    Capabilities:
        Unloading:
            realizedBy: "Unload"
            semantic_id: https://smartproductionlab.aau.dk/Capability/Unloading
    
    Skills:
        Unloading:
            description: "Unloading function for pharmaceutical primary packaging"
            semantic_id: "https://smartproductionlab.aau.dk/skills/Unloading"
            interface: "Unloading"
        Halt:
            description: "Halt the current operation"
            semantic_id: "https://smartproductionlab.aau.dk/skills/Halt"
            interface: "Halt"
        Occupy:
            description: "Occupy the system for exclusive use"
            semantic_id: "https://smartproductionlab.aau.dk/skills/Occupy"
            interface: "Occupy"
        Release:
            description: "Release the system from exclusive use"
            semantic_id: "https://smartproductionlab.aau.dk/skills/Release"
            interface: "Release"