planarTableAAS:
    idShort: planarTableAAS
    id: 'https://smartproductionlab.aau.dk/aas/planarTable'
    globalAssetId: 'https://smartproductionlab.aau.dk/assets/ZTM1NTAzNzQtMDZkNi00N2Q4LWI1YTktMGNhMmY0MDEyNTk4'
    derivedFrom: 'https://smartproductionlab.aau.dk/aas/templates/resource'
    assetType: 'https://smartproductionlab.aau.dk/Resource/CPS/MotionSystem/planarTable'
    serialNumber: 'PM-S1-2024-001'
    location: 'InnoLab, Nybrovej, AAU'
    AssetInterfacesDescription:
        InterfaceMQTT:
            Title: 'Planar Motors Shuttle'
            EndpointMetadata:
                base: 'mqtt://192.168.0.104:1883/NN/Nybrovej/InnoLab/Planar'
                contentType: 'application/json'
            InteractionMetadata:
                actions:
                    halt:
                        key: 'halt'
                        title: 'halt'
                        synchronous: 'true'
                        input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
                        forms:
                            contentType: 'application/json'
                            href: '/CMD/Halt'
                            op: 'invokeAction'
                            mqv_retain: 'false'
                            mqv_controlPacket: subscribe
                            mqv_qos: '2'                                              
                properties:
                    StationState:
                        key: 'StationState'
                        title: 'StationState'
                        output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/stationState.schema.json'
                        forms:
                            contentType: 'application/json'
                            href: '/DATA/State'
                            mqv_retain: 'false'
                            mqv_controlPacket: publish
                            mqv_qos: '0'

    Variables:
        PackMLState:
            semanticId: 'https://www.omac.org/packml/state'
            InterfaceReference: 'StationState'
            Field: 'State'

    Parameters:
    HierarchicalStructures:
        Name: 'BillOfMaterials'
        Archetype: 'OneDown'
        HasPart:
            planarTableShuttle1:
                globalAssetId: 'https://smartproductionlab.aau.dk/assets/ODYwM2Q2YjYtYmUzOS00NTAxLWFhZDktYjc1MjhhMzUzOGNm'
            planarTableShuttle2:
                globalAssetId: 'https://smartproductionlab.aau.dk/assets/OTZhZGNiZDAtNTNhNS00YmJhLThiNDctMzFjYzM3OGNiNTMw'
            planarTableShuttle3:
                globalAssetId: 'https://smartproductionlab.aau.dk/assets/YjY3ZTJjZGEtZDYxMC00ZDJjLTlkYjYtOGUyNGE4NWVlNTBi'
    
    Capabilities:
    
    Skills:
        halt:
            description: "Halt all planar table operations"
            semantic_id: "https://smartproductionlab.aau.dk/skills/halt"
            interface: "halt"