processTemplate:
    idShort: processTemplate
    id: 'https://smartproductionlab.aau.dk/aas/processTemplate'
    globalAssetId: 'https://smartproductionlab.aau.dk/assets/ZGUyNzVkMmItZjJjYy00NTI3LThiNDQtNTA0MDAwNTc1YmE5'
    derivedFrom: 'https://smartproductionlab.aau.dk/aas/templates/resource'
    assetType: 'https://smartproductionlab.aau.dk/Process/Production'
    serialNumber: 'AAU-PT-2024-001'
    location: 'InnoLab, Nybrovej, AAU'
    Process:
        ProduceHgH:
            requiredCapabilities:
                - Move:
                    semantic_id: "https://smartproductionlab.aau.dk/Capability/MoveToPosition"
                    asset: "planarShuttle2"
                - Loading:
                    semantic_id: "https://smartproductionlab.aau.dk/Capability/Loading"
                    asset: "loadingModule"
                - Dispensing:
                    semantic_id: "https://smartproductionlab.aau.dk/Capabilities/Dispensing"
                    asset: "dispensingModule"
                - Stoppering:
                    semantic_id: "https://smartproductionlab.aau.dk/Capability/Stoppering"
                    asset: "stopperingModule"
                - QualityControl:
                    semantic_id: "https://smartproductionlab.aau.dk/Capability/QualityControl"
                    asset: "cameraModule"
                - Unloading:
                    semantic_id: "https://smartproductionlab.aau.dk/Capability/Unloading"
                    asset: "unloadingModule"
            comment: "Pick and place capability"
            policy: "https://aausmartproductionlab.github.io/AP2030-UNS/BTDescriptions/productionTask.xml"
            relations:
                requires:
                    target: "https://smartproductionlab.aau.dk/aas/Resource/CPPM/MotionSystem"
                    target: "https://smartproductionlab.aau.dk/aas/Resource/CPS/MotionUnit"
                    target: "https://smartproductionlab.aau.dk/aas/Resource/CPPM/LoadingModule"
                    target: "https://smartproductionlab.aau.dk/aas/Resource/CPPM/DispensingModule"
                    target: "https://smartproductionlab.aau.dk/aas/Resource/CPPM/StopperingModule"
                    target: "https://smartproductionlab.aau.dk/aas/Resource/CPPM/QCModule"
                    target: "https://smartproductionlab.aau.dk/aas/Resource/CPPM/UnloadingModule"
                    target: "https://smartproductionlab.aau.dk/Capability/MoveToPosition"
                    target: "https://smartproductionlab.aau.dk/Capability/Loading"
                    target: "https://smartproductionlab.aau.dk/Capabilities/Dispensing"
                    target: "https://smartproductionlab.aau.dk/Capability/Stoppering"
                    target: "https://smartproductionlab.aau.dk/Capability/QualityControl"
                    target: "https://smartproductionlab.aau.dk/Capability/Unloading"
            properties:
                MaxVelocity:
                    min: 0
                    max: 500
                    description: "Maximum velocity in mm/s"